version: "3.9"

services:
    app:
        build:
            dockerfile: Dockerfile
            context: .
        restart: always
        container_name: app   
        depends_on: 
            - postgres
        volumes:
            - .:/usr/src/app       
        environment:
            PORT: 3000
            DATABASE_URL: postgres://admin:admin@postgres:5432/db
        ports:
            - "8080:3000"

    postgres:
        image: postgres:13
        restart: always
        container_name: postgres
        volumes: 
            - /pg_data:/var/lib/postgresql/data
        ports:
            - "35000:5432" 
        environment: 
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: db   