export const FETCH_HOTDOGS = 'FETCH_HOTDOGS';
export const FETCH_HOTDOGS_SUCCESS = 'FETCH_HOTDOGS_SUCCESS';
export const FETCH_HOTDOGS_ERROR = 'FETCH_HOTDOGS_ERROR';

export const ADD_HOTDOG = 'ADD_HOTDOG';
export const ADD_HOTDOG_SUCCESS = 'ADD_HOTDOG_SUCCESS';
export const ADD_HOTDOG_ERROR = 'ADD_HOTDOG_ERROR';

export const UPDATE_HOTDOG = 'UPDATE_HOTDOG';
export const UPDATE_HOTDOG_SUCCESS = 'UPDATE_HOTDOG_SUCCESS';
export const UPDATE_HOTDOG_ERROR = 'UPDATE_HOTDOG_ERROR';

export const DELETE_HOTDOG = 'DELETE_HOTDOG';
export const DELETE_HOTDOG_SUCCESS = 'DELETE_HOTDOG_SUCCESS';
export const DELETE_HOTDOG_ERROR = 'DELETE_HOTDOG_ERROR';